# Generated by Django 2.0.7 on 2018-11-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kw_ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20)),
                ('ad_type', models.CharField(default='1', max_length=10)),
                ('content', models.TextField()),
                ('url', models.TextField()),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
