# Generated by Django 2.0.7 on 2018-11-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyw', '0003_kw_ad_log_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='kw_ad',
            name='filename',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='kw_ad',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='kw_ad',
            name='keyword',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='kw_ad',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
