# Generated by Django 2.0.7 on 2018-11-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyw', '0005_kw_ad_filename_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='kw_ad',
            name='provider',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
