# Generated by Django 2.0.7 on 2018-11-09 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct', models.CharField(max_length=20)),
                ('post', models.BooleanField(default=True)),
                ('active', models.CharField(default='1', max_length=10)),
                ('parent_id', models.CharField(blank=True, max_length=50)),
                ('date', models.DateTimeField()),
                ('last_update', models.DateTimeField(null=True)),
                ('content', models.TextField()),
                ('up', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('reply_num', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.CharField(default='1', max_length=10)),
                ('user_id', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msg.Comments')),
            ],
        ),
    ]
