# Generated by Django 2.0.7 on 2018-11-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_ip',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
