# Generated by Django 2.0.7 on 2018-11-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testdj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('date_created', models.DateField()),
                ('block', models.IntegerField()),
                ('creator', models.CharField(max_length=20)),
                ('time_created', models.DateTimeField(blank=True, null=True)),
                ('group1', models.CharField(max_length=10)),
                ('group2', models.CharField(max_length=10)),
                ('group3', models.CharField(max_length=10)),
                ('group4', models.CharField(max_length=10)),
                ('group5', models.CharField(max_length=10)),
            ],
        ),
    ]
