# Generated by Django 2.0.7 on 2018-11-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdj',
            name='time_logged',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='testdj',
            name='time_created',
            field=models.DateTimeField(null=True),
        ),
    ]
