# Generated by Django 2.0.7 on 2018-12-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20181108_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdj',
            name='group6',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='testdj',
            name='group1',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='testdj',
            name='group2',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='testdj',
            name='group3',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='testdj',
            name='group4',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='testdj',
            name='group5',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
