# Generated by Django 2.0.7 on 2018-11-09 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='acct_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_name', models.CharField(max_length=20)),
                ('comm_num', models.IntegerField(default=0)),
                ('acct_info1', models.CharField(default=None, max_length=10)),
                ('acct_info2', models.CharField(default=None, max_length=10)),
                ('acct_info3', models.CharField(default=None, max_length=10)),
                ('acct_info4', models.CharField(default=None, max_length=10)),
                ('acct_info5', models.CharField(default=None, max_length=10)),
                ('dapp', models.BooleanField(default=False)),
                ('dapp_desc', models.TextField(blank=True, default='')),
                ('dapp_name', models.CharField(default='', max_length=50)),
                ('dapp_url', models.CharField(default='', max_length=50)),
                ('acct_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='search.Testdj')),
            ],
        ),
    ]
