# Generated by Django 2.0.7 on 2018-11-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acct_info',
            old_name='acct_id',
            new_name='acct',
        ),
    ]
