# Generated by Django 2.0.7 on 2018-11-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0002_auto_20181109_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acct_info',
            name='acct_info1',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='acct_info',
            name='acct_info2',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='acct_info',
            name='acct_info3',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='acct_info',
            name='acct_info4',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='acct_info',
            name='acct_info5',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
