# Generated by Django 2.0.7 on 2018-12-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0003_auto_20181109_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acct_info',
            name='acct_info2',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
