# Generated by Django 2.0.7 on 2018-12-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0005_auto_20181201_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acct_info',
            name='acct_info2',
            field=models.CharField(default=None, max_length=80, null=True),
        ),
    ]
