# Generated by Django 2.0.7 on 2018-12-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0006_auto_20181201_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acct_info',
            name='dapp',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='acct_info',
            name='dapp_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='acct_info',
            name='dapp_url',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
