# Generated by Django 2.0.7 on 2018-12-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0008_auto_20181201_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acct_info',
            name='dapp_desc',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
