# Generated by Django 2.0.7 on 2018-12-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0009_auto_20181201_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acct_info',
            name='acct_info1',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='acct_info',
            name='acct_info2',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
